package sv.edu.udb.Cuponera.hibernate;
// Generated Jun 19, 2020 11:51:27 PM by Hibernate Tools 5.4.14.Final

/**
 * ClienteConfirmToken generated by hbm2java
 */
public class ClienteConfirmToken implements java.io.Serializable {

	private Integer tokenId;
	private Clientes clientes;
	private String token;

	public ClienteConfirmToken() {
	}

	public ClienteConfirmToken(Clientes clientes, String token) {
		this.clientes = clientes;
		this.token = token;
	}

	public Integer getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(Integer tokenId) {
		this.tokenId = tokenId;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
