package sv.edu.udb.Cuponera.hibernate;
// Generated Jun 19, 2020 11:51:27 PM by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private Integer clienteId;
	private String username;
	private String nombres;
	private String apellidos;
	private String dui;
	private String telefono;
	private String correo;
	private String contrasena;
	private int confirmado;
	private Set clienteConfirmTokens = new HashSet(0);
	private Set cuponeses = new HashSet(0);

	public Clientes() {
	}

	public Clientes(String username, String nombres, String apellidos, String dui, String telefono, String correo,
			String contrasena, int confirmado) {
		this.username = username;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.dui = dui;
		this.telefono = telefono;
		this.correo = correo;
		this.contrasena = contrasena;
		this.confirmado = confirmado;
	}

	public Clientes(String username, String nombres, String apellidos, String dui, String telefono, String correo,
			String contrasena, int confirmado, Set clienteConfirmTokens, Set cuponeses) {
		this.username = username;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.dui = dui;
		this.telefono = telefono;
		this.correo = correo;
		this.contrasena = contrasena;
		this.confirmado = confirmado;
		this.clienteConfirmTokens = clienteConfirmTokens;
		this.cuponeses = cuponeses;
	}

	public Integer getClienteId() {
		return this.clienteId;
	}

	public void setClienteId(Integer clienteId) {
		this.clienteId = clienteId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDui() {
		return this.dui;
	}

	public void setDui(String dui) {
		this.dui = dui;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public int getConfirmado() {
		return this.confirmado;
	}

	public void setConfirmado(int confirmado) {
		this.confirmado = confirmado;
	}

	public Set getClienteConfirmTokens() {
		return this.clienteConfirmTokens;
	}

	public void setClienteConfirmTokens(Set clienteConfirmTokens) {
		this.clienteConfirmTokens = clienteConfirmTokens;
	}

	public Set getCuponeses() {
		return this.cuponeses;
	}

	public void setCuponeses(Set cuponeses) {
		this.cuponeses = cuponeses;
	}

}
