package sv.edu.udb.Cuponera.hibernate;
// Generated Jun 19, 2020 11:51:27 PM by Hibernate Tools 5.4.14.Final

/**
 * Cupones generated by hbm2java
 */
public class Cupones implements java.io.Serializable {

	private String cuponId;
	private Clientes clientes;
	private Promociones promociones;
	private int estado;

	public Cupones() {
	}

	public Cupones(String cuponId, Clientes clientes, Promociones promociones, int estado) {
		this.cuponId = cuponId;
		this.clientes = clientes;
		this.promociones = promociones;
		this.estado = estado;
	}

	public String getCuponId() {
		return this.cuponId;
	}

	public void setCuponId(String cuponId) {
		this.cuponId = cuponId;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Promociones getPromociones() {
		return this.promociones;
	}

	public void setPromociones(Promociones promociones) {
		this.promociones = promociones;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

}
