package sv.edu.udb.Cuponera.hibernate;
// Generated Jun 19, 2020 11:51:27 PM by Hibernate Tools 5.4.14.Final

/**
 * Dependientes generated by hbm2java
 */
public class Dependientes implements java.io.Serializable {

	private Integer dependienteId;
	private String nombre;
	private String apellidos;
	private String correo;
	private String contrasena;
	private String username;

	public Dependientes() {
	}

	public Dependientes(String nombre, String apellidos, String correo, String contrasena, String username) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.correo = correo;
		this.contrasena = contrasena;
		this.username = username;
	}

	public Integer getDependienteId() {
		return this.dependienteId;
	}

	public void setDependienteId(Integer dependienteId) {
		this.dependienteId = dependienteId;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
