package sv.edu.udb.Cuponera.hibernate;
// Generated Jun 19, 2020 11:51:27 PM by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas implements java.io.Serializable {

	private String empresaId;
	private Rubros rubros;
	private String nombre;
	private String direccion;
	private String telefono;
	private String correo;
	private double comision;
	private Set promocioneses = new HashSet(0);

	public Empresas() {
	}

	public Empresas(String empresaId, Rubros rubros, String nombre, String direccion, String telefono, String correo,
			double comision) {
		this.empresaId = empresaId;
		this.rubros = rubros;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
		this.comision = comision;
	}

	public Empresas(String empresaId, Rubros rubros, String nombre, String direccion, String telefono, String correo,
			double comision, Set promocioneses) {
		this.empresaId = empresaId;
		this.rubros = rubros;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.correo = correo;
		this.comision = comision;
		this.promocioneses = promocioneses;
	}

	public String getEmpresaId() {
		return this.empresaId;
	}

	public void setEmpresaId(String empresaId) {
		this.empresaId = empresaId;
	}

	public Rubros getRubros() {
		return this.rubros;
	}

	public void setRubros(Rubros rubros) {
		this.rubros = rubros;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public double getComision() {
		return this.comision;
	}

	public void setComision(double comision) {
		this.comision = comision;
	}

	public Set getPromocioneses() {
		return this.promocioneses;
	}

	public void setPromocioneses(Set promocioneses) {
		this.promocioneses = promocioneses;
	}

}
