package sv.edu.udb.Cuponera.hibernate;
// Generated Jun 19, 2020 11:51:27 PM by Hibernate Tools 5.4.14.Final

/**
 * JustificacionRechazos generated by hbm2java
 */
public class JustificacionRechazos implements java.io.Serializable {

	private Integer justificacionId;
	private Promociones promociones;
	private String descripcion;

	public JustificacionRechazos() {
	}

	public JustificacionRechazos(Promociones promociones, String descripcion) {
		this.promociones = promociones;
		this.descripcion = descripcion;
	}

	public Integer getJustificacionId() {
		return this.justificacionId;
	}

	public void setJustificacionId(Integer justificacionId) {
		this.justificacionId = justificacionId;
	}

	public Promociones getPromociones() {
		return this.promociones;
	}

	public void setPromociones(Promociones promociones) {
		this.promociones = promociones;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
