package sv.edu.udb.Cuponera.hibernate;
// Generated Jun 19, 2020 11:51:27 PM by Hibernate Tools 5.4.14.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Promociones generated by hbm2java
 */
public class Promociones implements java.io.Serializable {

	private Integer promoId;
	private Empresas empresas;
	private double precioRegular;
	private double precioOferta;
	private Date fechaInicio;
	private Date fechaFinal;
	private Date fechaLimite;
	private Integer cantidadLimite;
	private String descripcion;
	private int statusCupon;
	private Set cuponeses = new HashSet(0);
	private Set justificacionRechazoses = new HashSet(0);

	public Promociones() {
	}

	public Promociones(Empresas empresas, double precioRegular, double precioOferta, Date fechaInicio, Date fechaFinal,
			Date fechaLimite, String descripcion, int statusCupon) {
		this.empresas = empresas;
		this.precioRegular = precioRegular;
		this.precioOferta = precioOferta;
		this.fechaInicio = fechaInicio;
		this.fechaFinal = fechaFinal;
		this.fechaLimite = fechaLimite;
		this.descripcion = descripcion;
		this.statusCupon = statusCupon;
	}

	public Promociones(Empresas empresas, double precioRegular, double precioOferta, Date fechaInicio, Date fechaFinal,
			Date fechaLimite, Integer cantidadLimite, String descripcion, int statusCupon, Set cuponeses,
			Set justificacionRechazoses) {
		this.empresas = empresas;
		this.precioRegular = precioRegular;
		this.precioOferta = precioOferta;
		this.fechaInicio = fechaInicio;
		this.fechaFinal = fechaFinal;
		this.fechaLimite = fechaLimite;
		this.cantidadLimite = cantidadLimite;
		this.descripcion = descripcion;
		this.statusCupon = statusCupon;
		this.cuponeses = cuponeses;
		this.justificacionRechazoses = justificacionRechazoses;
	}

	public Integer getPromoId() {
		return this.promoId;
	}

	public void setPromoId(Integer promoId) {
		this.promoId = promoId;
	}

	public Empresas getEmpresas() {
		return this.empresas;
	}

	public void setEmpresas(Empresas empresas) {
		this.empresas = empresas;
	}

	public double getPrecioRegular() {
		return this.precioRegular;
	}

	public void setPrecioRegular(double precioRegular) {
		this.precioRegular = precioRegular;
	}

	public double getPrecioOferta() {
		return this.precioOferta;
	}

	public void setPrecioOferta(double precioOferta) {
		this.precioOferta = precioOferta;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public Date getFechaLimite() {
		return this.fechaLimite;
	}

	public void setFechaLimite(Date fechaLimite) {
		this.fechaLimite = fechaLimite;
	}

	public Integer getCantidadLimite() {
		return this.cantidadLimite;
	}

	public void setCantidadLimite(Integer cantidadLimite) {
		this.cantidadLimite = cantidadLimite;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getStatusCupon() {
		return this.statusCupon;
	}

	public void setStatusCupon(int statusCupon) {
		this.statusCupon = statusCupon;
	}

	public Set getCuponeses() {
		return this.cuponeses;
	}

	public void setCuponeses(Set cuponeses) {
		this.cuponeses = cuponeses;
	}

	public Set getJustificacionRechazoses() {
		return this.justificacionRechazoses;
	}

	public void setJustificacionRechazoses(Set justificacionRechazoses) {
		this.justificacionRechazoses = justificacionRechazoses;
	}

}
