package sv.edu.udb.Cuponera.hibernate;
// Generated Jun 19, 2020 11:51:27 PM by Hibernate Tools 5.4.14.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Rubros generated by hbm2java
 */
public class Rubros implements java.io.Serializable {

	private Integer rubroId;
	private String rubro;
	private Set empresases = new HashSet(0);

	public Rubros() {
	}

	public Rubros(String rubro) {
		this.rubro = rubro;
	}

	public Rubros(String rubro, Set empresases) {
		this.rubro = rubro;
		this.empresases = empresases;
	}

	public Integer getRubroId() {
		return this.rubroId;
	}

	public void setRubroId(Integer rubroId) {
		this.rubroId = rubroId;
	}

	public String getRubro() {
		return this.rubro;
	}

	public void setRubro(String rubro) {
		this.rubro = rubro;
	}

	public Set getEmpresases() {
		return this.empresases;
	}

	public void setEmpresases(Set empresases) {
		this.empresases = empresases;
	}

}
